CREATE TYPE "AccountCategory" AS ENUM (
  'CURRENT_ASSET',
  'FIXED_ASSET',
  'OTHER_ASSET',
  'CURRENT_LIABILITY',
  'LONG_TERM_LIABILITY',
  'OWNER_EQUITY',
  'SALES_REVENUE',
  'OTHER_REVENUE',
  'COGS',
  'OPERATING_EXPENSE',
  'NON_OPERATING_EXPENSE',
  'TAX_EXPENSE'
);

ALTER TABLE "ChartOfAccount" ADD COLUMN "accountCategory" "AccountCategory";
